//////////////////////////////////////////////////////////
//   This class has been generated by TFile::MakeProject
//     (Tue Feb 25 18:16:23 2020 by ROOT version 6.18/04)
//      from the StreamerInfo in file /eos/user/l/ldinoto/ECALSTT_FHC_Horn1Y_r1_001_5e16.200102.edep.root
//////////////////////////////////////////////////////////


#ifndef TG4PrimaryVertex_h
#define TG4PrimaryVertex_h
class TG4PrimaryVertex;

#include "Rtypes.h"
#include "TObject.h"
#include "Riostream.h"
#include <vector>
#include "TG4PrimaryParticle.h"
#include "TG4PrimaryVertex.h"
#include "TLorentzVector.h"
#include <string>

class TG4PrimaryVertex : public TObject {

public:
// Nested classes declaration.

public:
// Data Members.
   vector<TG4PrimaryParticle> Particles;    //
   vector<TG4PrimaryVertex>   Informational;    //
   TLorentzVector             Position;         //
   string                     GeneratorName;    //
   string                     Reaction;         //
   string                     Filename;         //
   int                        InteractionNumber;    //
   float                      CrossSection;         //
   float                      DiffCrossSection;     //
   float                      Weight;               //
   float                      Probability;          //

   TG4PrimaryVertex();
   TG4PrimaryVertex(TG4PrimaryVertex && ) = default;
   TG4PrimaryVertex(const TG4PrimaryVertex & );
   virtual ~TG4PrimaryVertex();

   ClassDef(TG4PrimaryVertex,3); // Generated by MakeProject.
};
#endif
