//////////////////////////////////////////////////////////
//   This class has been generated by TFile::MakeProject
//     (Tue Feb 25 18:16:23 2020 by ROOT version 6.18/04)
//      from the StreamerInfo in file /eos/user/l/ldinoto/ECALSTT_FHC_Horn1Y_r1_001_5e16.200102.edep.root
//////////////////////////////////////////////////////////


#ifndef TG4PrimaryParticle_h
#define TG4PrimaryParticle_h
class TG4PrimaryParticle;

#include "Rtypes.h"
#include "TObject.h"
#include "Riostream.h"
#include <string>
#include "TLorentzVector.h"

class TG4PrimaryParticle : public TObject {

public:
// Nested classes declaration.

public:
// Data Members.
   int         TrackId;     //
   string      Name;        //
   int         PDGCode;     //
   TLorentzVector Momentum;    //

   TG4PrimaryParticle();
   TG4PrimaryParticle(TG4PrimaryParticle && ) = default;
   TG4PrimaryParticle(const TG4PrimaryParticle & );
   virtual ~TG4PrimaryParticle();

   ClassDef(TG4PrimaryParticle,2); // Generated by MakeProject.
};
#endif
